from flask import Flask, render_template
from os import getenv
import backend

app = Flask(__name__)
db_conn_status = False
fortune = None


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    try:
        backend.db.connect()
        global fortune
        fortune = backend.read_fortune()
    except backend.pw.OperationalError as e:
        print(f"An error ocurred while connecting to the database: {e}")
    else:
        print("Successfully connected to the database.")
        global db_conn_status
        db_conn_status = True


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not backend.db.is_closed():
        backend.db.close()


@app.route('/')
def index():
    return render_template(
        'index.html', fortune=fortune, connected=db_conn_status,
        app_version=getenv("APP_VERSION"), app_env=getenv("APP_ENV")
    )
